package:
  name: pyrism
  version: "0.0.1"

source:
  git_rev: v0.0.1
  git_url: https://github.com/pyrismguy/pyrism.git

requirements:
  build:
    - python
    - setuptools
    - cython
    - pySDL2
    - pyopengl
    - pillow
  run:
    - python

about:
  home: https://github.com/pyrismguy/pyrism
  license: BSD
  license_file: LICENSE